# -*- coding: utf-8 -*-
"""PRCP-1020-House Price Pred Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCk3zO9oSLrlrD_kstQEKBt9RB1R2DKK

PROJECT 1

Problem Statement

Task 1:-  Prepare a complete data analysis report on the given data.

Task 2:-

  a) Create a robust machine learning algorithm to accurately predict the
price of the house given the various factors across the market.

   b) Determine the relationship between the house features and how the
price varies based on this.

Task3:-   Come up with suggestions for the customer to buy the house according
to the area, price and other requirements.

Dataset Description and Link:

Ask a home buyer to describe their dream house, and they probably won't begin with
the height of the basement ceiling or the proximity to an east-west railroad. But this
playground competition's dataset proves that much more influences price negotiations
than the number of bedrooms or a white-picket fence.

With 79 explanatory variables describing (almost) every aspect of residential homes in
Ames, Iowa, this competition challenges you to predict the final price of each home.

Practice Skills

● Creative feature engineering

● Advanced regression techniques like random forest and gradient boosting

Attribute Information

● SalePrice - the property's sale price in dollars. This is the target variable that
you're trying to predict.

● MSSubClass: The building class

● MSZoning: The general zoning classification

● LotFrontage: Linear feet of street connected to property

● LotArea: Lot size in square feet

● Street: Type of road access

● Alley: Type of alley access

● LotShape: General shape of property

● LandContour: Flatness of the property

● Utilities: Type of utilities available

● LotConfig: Lot configuration

● LandSlope: Slope of property

● Neighborhood: Physical locations within Ames city limits

● Condition1: Proximity to main road or railroad

● Condition2: Proximity to main road or railroad (if a second is present)

● BldgType: Type of dwelling

● HouseStyle: Style of dwelling

● OverallQual: Overall material and finish quality

● OverallCond: Overall condition rating

● YearBuilt: Original construction date

● YearRemodAdd: Remodel date

● RoofStyle: Type of roof

● RoofMatl: Roof material

● Exterior1st: Exterior covering on house

● Exterior2nd: Exterior covering on house (if more than one material)

● MasVnrType: Masonry veneer type

● MasVnrArea: Masonry veneer area in square feet

● ExterQual: Exterior material quality

● ExterCond: Present condition of the material on the exterior

● Foundation: Type of foundation

● BsmtQual: Height of the basement

● BsmtCond: General condition of the basement

● BsmtExposure: Walkout or garden level basement walls

● BsmtFinType1: Quality of basement finished area

● BsmtFinSF1: Type 1 finished square feet

● BsmtFinType2: Quality of second finished area (if present)

● BsmtFinSF2: Type 2 finished square feet

● BsmtUnfSF: Unfinished square feet of basement area


● TotalBsmtSF: Total square feet of basement area

● Heating: Type of heating

● HeatingQC: Heating quality and condition

● CentralAir: Central air conditioning

● Electrical: Electrical system

● 1stFlrSF: First Floor square feet

● 2ndFlrSF: Second floor square feet

● LowQualFinSF: Low quality finished square feet (all floors)

● GrLivArea: Above grade (ground) living area square feet

● BsmtFullBath: Basement full bathrooms

● BsmtHalfBath: Basement half bathrooms

● FullBath: Full bathrooms above grade

● HalfBath: Half baths above grade

● Bedroom: Number of bedrooms above basement level

● Kitchen: Number of kitchens

● KitchenQual: Kitchen quality

● TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)

● Functional: Home functionality rating

● Fireplaces: Number of fireplaces

● FireplaceQu: Fireplace quality

● GarageType: Garage location

● GarageYrBlt: Year garage was built

● GarageFinish: Interior finish of the garage

● GarageCars: Size of garage in car capacity

● GarageArea: Size of garage in square feet

● GarageQual: Garage quality

● GarageCond: Garage condition

● PavedDrive: Paved driveway

● WoodDeckSF: Wood deck area in square feet

● OpenPorchSF: Open porch area in square feet

● EnclosedPorch: Enclosed porch area in square feet

● 3SsnPorch: Three season porch area in square feet

● ScreenPorch: Screen porch area in square feet

● PoolArea: Pool area in square feet

● PoolQC: Pool quality

● Fence: Fence quality

● MiscFeature: Miscellaneous feature not covered in other categories

● MiscVal: $Value of miscellaneous feature

● MoSold: Month Sold

● YrSold: Year Sold


● SaleType: Type of sale

● SaleCondition: Condition of sale

Model Comparison Report

Create a report stating the performance of multiple models for house price
prediction and suggest the best model for production.

Report on Challenges faced

Create a report which should include the challenges faced on data and
what techniques were used with proper reasoning.

Note:- All the above tasks must be created on a single jupyter notebook
and the same should be shared as part of final submission of the project.

ANSWERS:
"""

from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/drive/MyDrive/data.csv')
data

"""# BASIC CHECKS"""

data.head()

data.tail()

data.columns

data.dtypes

data.shape

data.info()

"""# DATA PREPROCESSING"""

data.describe().T

"""
#              **DESCRIPTION**:



* Target Variable: SalePrice

* Numerical data columns : Id , MSSubClass , LotArea , OverallQual ,              
     OverallCond, YearBuilt , YearRemodAdd , MasVnrArea, BsmtFinSF1, BsmtFinSF2 , BsmtUnfSF , TotalBsmtSF , 1stFlrSF ,  2ndFlrSF , LowQualFinSF, GrLivArea , BsmtFullBath , BsmtHalfBath , FullBath , HalfBath , BedroomAbvGr , KitchenAbvGr , TotRmsAbvGrd , Fireplaces , GarageYrBlt , GarageCars , GarageArea , WoodDeckSF, OpenPorchSF ,EnclosedPorch , 3SsnPorch , ScreenPorch, PoolArea ,  MiscVal, MoSold, YrSold ,  SalePrice.

* categorical data columns : MSZoning, Street, Alley, LotShape , LandContour, Utilities, LotConfig , LandSlope, Neighborhood,      Condition1, Condition2, BldgType,
      HouseStyle,RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType,
      ExterQual, ExterCond, Foundation, BsmtQual,  BsmtCond, BsmtExposure,
      BsmtFinType1, BsmtFinType2, Heating,HeatingQC, CentralAir, Electrical, KitchenQual, Functional, FireplaceQu, GarageType, GarageFinish, GarageQual,GarageCond, PavedDrive, PoolQC,Fence, MiscFeature, SaleType,  SaleCondition.

* Many columns contain missing values

* Dataset contains 1460 rows and 81 columns."""

s=pd.DataFrame(data.isnull().sum())

s

s[s[0]>0]

"""# HANDLING MISSING VALUES"""

data['LotFrontage'] = data['LotFrontage'].fillna(data['LotFrontage'].median())

data['MasVnrArea'] = data['MasVnrArea'].fillna(data['MasVnrArea'].median())

data['GarageYrBlt'] = data['GarageYrBlt'].fillna(data['GarageYrBlt'].median())

cat_cols=['MasVnrType','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Electrical','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond']
for i in cat_cols:
    data[i]=data[i].fillna(data[i].mode()[0])

data.isnull().sum()

data.drop(['PoolQC','MiscFeature','Alley','Fence','Id'],axis=1,inplace=True)

data.isnull().sum()[data.isnull().sum()>0]

data.duplicated().sum()

"""# Statistical Analysis:

* The dataset contains 1460 observations and 81 features.
* It includes numerical and categorical variables.
* Several columns contain missing values, especially PoolQC, MiscFeature, Alley, Fence, and FireplaceQu.
* Numerical features have different scales, so feature scaling is required before training distance-based models such as KNN.
* Some numerical variables, including SalePrice, are positively skewed.
* Strong positive correlations with SalePrice are observed for variables such as OverallQual, GrLivArea, GarageCars, GarageArea, and TotalBsmtSF.
* Some features contain outliers, particularly GrLivArea, LotFrontage, and LotArea.
* Categorical features were encoded using manual encoding, frequency encoding, and label encoding before model training.
* Missing values and outliers were handled during preprocessing to improve model performance.
"""

plt.figure(figsize=(8,5))
sns.histplot(data['SalePrice'], kde=True)
plt.title('Distribution of SalePrice')
plt.show()

"""#         INSIGHT

* SalePrice is right-skewed (positively skewed).

* Most house prices are concentrated between 100,000 and 200,000.

* There is a long tail extending to the right (up to around 750,000).

* This histogram has many high-value observations stretching the right side.
"""

num_col = data.select_dtypes(include=['int64','float64']).columns

for col in num_col:
    plt.figure(figsize=(6,4))
    sns.histplot(data[col], kde=True)
    plt.title(col)
    plt.show()

"""| Column      | Distribution          |
| ----------- | --------------------- |
| SalePrice   | Right Skewed          |
| LotArea     | Right Skewed          |
| GrLivArea   | Right Skewed          |

BOX PLOT FOR OUTLIER HANDLING
"""

num_data=['MSSubClass', 'LotFrontage','LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF','LowQualFinSF',
        'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath','HalfBath', 'BedroomAbvGr','KitchenAbvGr',
        'TotRmsAbvGrd', 'Fireplaces','GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch','3SsnPorch', 'ScreenPorch','PoolArea','MiscVal', 'MoSold', 'YrSold',  'SalePrice']

plt.figure(figsize=(15,10),facecolor='white')
plotnumber=1
for i in num_data:
    if plotnumber<=40:
        ax=plt.subplot(8,5,plotnumber)
        sns.boxplot(x=data[i])
        plt.xlabel(i,fontsize=10)
        plt.ylabel('count',fontsize=10)
    plotnumber+=1
plt.tight_layout()

"""OUTLIERS HANDLING:"""

num_data=[ 'MSSubClass', 'LotFrontage','LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF','LowQualFinSF',
        'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath','HalfBath', 'BedroomAbvGr','KitchenAbvGr',
        'TotRmsAbvGrd', 'Fireplaces','GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch','3SsnPorch', 'ScreenPorch','PoolArea','MiscVal', 'MoSold', 'YrSold',  'SalePrice']

for i in num_data:
    print(i)

    Q1=data[i].quantile(0.25)
    print('lower_limit',Q1)
    Q3=data[i].quantile(0.75)
    print('upper_limit',Q3)

    IQR=Q3-Q1
    print(IQR)

    lower_limit=Q1-1.5*IQR
    print('lower_limit',lower_limit)
    upper_limit=Q3+1.5*IQR
    print('upper_limit',upper_limit)

    lower_outlier=len(data[data[i]<lower_limit])
    upper_outlier=len(data[data[i]>upper_limit])

    result=(lower_outlier + upper_outlier)/len(data)
    print(result)

    if result<0.05:
        data.loc[data[i] < lower_limit, i] = data[i].median()
        data.loc[data[i] > upper_limit, i] = data[i].median()
        print(data[i].median())
    else:
        print('outlier is not handled in',i)
    print('****************************************************')

plt.figure(figsize=(15,10),facecolor='white')
plotnumber=1
for i in num_data:
    if plotnumber<=40:
        ax=plt.subplot(8,5,plotnumber)
        sns.boxplot(x=data[i])
        plt.xlabel(i,fontsize=10)
        plt.ylabel('count',fontsize=10)
    plotnumber+=1
plt.tight_layout()

"""# OUTLIERS ARE HANDLED IN COLUMNS:

* LotArea
* OverallQual
* YearBuilt
* YearRemodAdd
* BsmtFinSF1
* BsmtUnfSF
* TotalBsmtSF
* 1stFlrSF
* 2ndFlrSF
* LowQualFinSF
* GrLivArea
* BsmtFullBath
* FullBath
* HalfBath
* BedroomAbvGr
* KitchenAbvGr
* TotRmsAbvGrd
* Fireplaces
* GarageYrBlt
* GarageCars
* GarageArea
* WoodDeckSF
* 3SsnPorch
* PoolArea
* Miscval
* MoSold
* YrSold
* SalePrice.




# OUTLIERS ARE NOT HANDLED IN COLUMNS:

* MSSubClass
* LotFrontage
* OverallCond
* MasVnrArea
* BsmtFinSF2
* BsmtHalfBath
* OpenPorchSF
* EnclosedPorch
* ScreenPorch

# EDA:

# UNIVARIENT GRAPH FOR NUMERICAL AND CATEGORICAL DATA :

# NUMERICAL DATA

Continuous data:
"""

num_data_con=['LotFrontage','LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF',
              '2ndFlrSF','LowQualFinSF','GrLivArea','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch',
              'ScreenPorch','PoolArea','MiscVal','SalePrice']

plt.figure(figsize=(15,10),facecolor='white')
plotnumber=1
for i in num_data_con:
    if plotnumber<=20:
        ax=plt.subplot(4,5,plotnumber)
        sns.histplot(x=data[i],kde=True)
        plt.xlabel(i,fontsize=10)
        plt.ylabel('count',fontsize=10)
    plotnumber+=1
plt.tight_layout()

"""# INSIGHT:

* Most numerical features are positively skewed (right-skewed), indicating that  a majority of houses have lower-to-moderate values, while a few houses have exceptionally high values.

* Several variables contain many zero values, such as:

  * MasVnrArea
  * BsmtFinSF2
  * 2ndFlrSF
  * OpenPorchSF
  * EnclosedPorch

* Variables such as
    * SalePrice
    * LotArea
    * GrLivArea
    * TotalBsmtSF
    * GarageArea
  
  shows wide distributions, indicating significant variation among properties.

* Year-based features (YearBuilt, YearRemodAdd, GarageYrBlt) are concentrated toward recent years, suggesting that a large proportion of houses are relatively modern or have been renovated recently.

* Potential outliers are visible in features such as:
    * LotArea
    * GrLivArea
    * GarageArea
    * TotalBsmtSF


* The dataset contains a mix of continuous and discrete numerical variables, providing diverse information about house size, quality, age, basement area, garage capacity, and other property characteristics.

 * The univariate analysis reveals that most numerical features are non-normally distributed and positively skewed, with several variables containing zero-inflated values and potential outliers.

 *  Year-related features indicate a predominance of newer or renovated houses, while house size and quality features exhibit substantial variability.

Discrete data:
"""

num_data_dis=['MSSubClass','OverallQual','OverallCond','YearBuilt','YearRemodAdd','BsmtFullBath','BsmtHalfBath','FullBath',
             'HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces','GarageYrBlt','GarageCars','MoSold','YrSold']

plt.figure(figsize=(20,25), facecolor='white')

plotnumber = 1

for col in num_data_dis:
    plt.subplot(6, 3, plotnumber)
    sns.countplot(data=data, x=col, palette='Set2')

    plt.title(f'Count Plot of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=45)

    plotnumber += 1

plt.tight_layout()
plt.show()

"""# INSIGHT:

* The count plots show that most discrete numerical features are clustered around a few common values, indicating that the housing market is dominated by typical family homes.
* Extreme values occur infrequently, suggesting that luxury or unusually small properties make up only a small portion of the dataset.
* Features such as OverallQual, GarageCars, FullBath, and TotRmsAbvGrd have distributions that support their importance as predictors of SalePrice.

# CATEGORICAL DATA
"""

cat_data=['MSZoning', 'Street','LotShape', 'LandContour','Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle','RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
        'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',  'BsmtCond', 'BsmtExposure',
        'BsmtFinType1', 'BsmtFinType2', 'Heating','HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
        'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive','SaleType',  'SaleCondition']

plt.figure(figsize=(20,25),facecolor='white')
plotnumber=1
for i in cat_data:
    if plotnumber<=45:
        ax=plt.subplot(9,5,plotnumber)
        sns.countplot(x=data[i],data=data)
        plt.xlabel(i,fontsize=10)
        plt.ylabel('count',fontsize=10)
        plt.xticks(rotation=90)
    plotnumber+=1
plt.tight_layout()

"""# INSIGHT:

* Most categorical variables are highly imbalanced, meaning one or two categories dominate the dataset.
     * MSZoning:  Mostly RL (Residential Low Density).
 * The majority of houses have regular property characteristics:
     * LotShape: Mostly Regular (Reg).
     * LandContour: Mostly Level (Lvl).
     * LandSlope: Mostly Gentle slope (Gtl).
     * Condition1 and Condition2: Predominantly Normal (Norm).
* Detached single-family homes dominate the dataset:
     * BldgType: Mostly 1Fam.
     * HouseStyle: Mostly 1Story and 2Story houses.
 * Certain neighborhoods contain significantly more houses than others, indicating an uneven geographical distribution of properties.
 * Modern construction materials and designs are predominant:
     * RoofStyle: Mostly Gable roofs.
     * RoofMatl: Mostly CompShg roofing material.
     * Exterior1st and Exterior2nd: Primarily VinylSd siding.
 * Quality-related features indicate average to good house quality:
    * ExterQual
    * KitchenQual
    * BsmtQual
    *  Mostly TA (Typical/Average) and Gd (Good).
 * Very few houses fall into Poor (Po) or Excellent (Ex) categories.
 * Most houses have standard amenities:
     * CentralAir: Majority have Central Air Conditioning (Y).
     * HeatingQC: Mostly Excellent (Ex) or Good (Gd).
     * Electrical: Predominantly SBrkr electrical systems.

 * The categorical feature analysis reveals that the dataset is dominated by standard residential properties with typical construction quality, paved streets, public utilities, central air conditioning, and average-to-good quality ratings.
  *  Most categorical variables are highly imbalanced, with a few categories accounting for the majority of observations.
  * These patterns suggest that the dataset primarily represents conventional suburban homes, while rare categories may require special handling during feature engineering and model development.

# BIVARIENT GRAPHS FOR NUMERICAL AND CATEGORICAL DATA :

# NUMERICAL DATA
"""

plt.figure(figsize=(20,15), facecolor='white')

plotnumber = 1

for col in num_data_con:
    plt.subplot(4,5, plotnumber)
    sns.scatterplot(data=data, x=col, y='SalePrice', color='royalblue')

    plt.title(f'{col} vs SalePrice')
    plt.xlabel(col)
    plt.ylabel('SalePrice')

    plotnumber += 1

plt.tight_layout()
plt.show()

"""INSIGHT:

* The scatter plots show the relationship between each continuous numerical feature and the target variable, SalePrice.
* GrLivArea shows a strong positive correlation with SalePrice; houses with larger above-ground living areas generally sell for higher prices.
* TotalBsmtSF has a positive relationship with SalePrice, indicating that larger basement areas are associated with more expensive houses.
* GarageArea also exhibits a positive trend, suggesting that homes with larger garages tend to have higher market values.
* 1stFlrSF demonstrates a moderate to strong positive relationship with SalePrice, where larger first-floor areas correspond to higher prices.
* LotArea has a weaker positive relationship with SalePrice due to considerable variation in lot sizes. Larger lots do not always result in proportionally higher prices.
* Features such as WoodDeckSF, OpenPorchSF, and MasVnrArea show a moderate positive association with SalePrice, but the data points are more widely scattered.
* Some features, including PoolArea, ScreenPorch, and MiscVal, display weak relationships with SalePrice because many observations have zero values.
* A few outliers are visible in variables such as GrLivArea and LotArea, where properties have unusually large values but do not follow the overall trend.
*  Some variables show little relationship with the target variable, while several features contain outliers.

# CATEGORICAL DATA
"""

plt.figure(figsize=(25,30),facecolor='white')
plotnumber=1
for i in cat_data:
    if plotnumber<=45:
        ax=plt.subplot(9,5,plotnumber)
        sns.violinplot(x=data[i], y=data['SalePrice'],palette='Set2')
        plt.xlabel(i,fontsize=20)
        plt.ylabel('count',fontsize=20)
        plt.xticks(rotation=90)
    plotnumber+=1
plt.tight_layout()

"""INSIGHTS:

* Neighborhood has a strong impact on SalePrice.

* Some neighborhoods show much higher median house prices and wider price distributions than others.

* Location appears to be one of the most influential factors affecting house prices.

* Quality-related features strongly influence SalePrice.

* ExterQual, KitchenQual, BsmtQual, GarageQual, and HeatingQC show a clear increase in SalePrice as quality improves from Fair (Fa) to Good (Gd) and Excellent (Ex).

* Houses with higher quality ratings generally sell at higher prices.

* Central Air Conditioning affects house prices.

* Houses with CentralAir = Y have noticeably higher SalePrice distributions compared to houses without central air.

* Garage-related features are important.
* Infrastructure-related features such as Street and PavedDrive show differences in house prices, with better infrastructure generally associated with higher values.
* Utilities provides minimal predictive value because nearly every house belongs to the same category.
* Features with very low variation (like Utilities) may contribute less to the predictive model than features with more diverse categories.

* GarageType, GarageFinish, and GarageQual show clear differences in SalePrice.
Finished garages and better garage quality are associated with higher-priced homes.

* Basement features influence house prices.

* Better basement quality (BsmtQual), exposure (BsmtExposure), and finishing types (BsmtFinType1) generally correspond to higher SalePrice values.

* Fireplace quality contributes positively.

* Houses with higher FireplaceQu ratings tend to have higher median SalePrices.
* Roof style and exterior materials show moderate influence.
* Certain roof styles and exterior materials are associated with higher house prices, although the effect is less pronounced than quality-related features.
* Several categorical variables are highly imbalanced.

* Features such as Street, Utilities, RoofMatl, and Electrical are dominated by one category, providing limited variation for analysis.


* The violin plot analysis indicates that house quality, neighborhood, basement characteristics, garage features, central air conditioning, and fireplace quality are among the most influential categorical factors affecting SalePrice.



"""

cat_data

num_data

"""ENCODING:"""

for i in cat_data:
    print(i)
    print(data[i].value_counts())
    print('**********************************')

"""# LABEL ENCODING:"""

from sklearn.preprocessing import LabelEncoder

lc=LabelEncoder()

label_cols = ['Street', 'CentralAir', 'Utilities', 'LandSlope', 'PavedDrive']

for col in label_cols:
    data[col] = lc.fit_transform(data[col])

"""# FREQUENCY ENCODING:"""

frequency_cols = [
    'MSZoning','LotShape','LandContour','LotConfig','Neighborhood',
    'Condition1','Condition2','BldgType','HouseStyle','RoofStyle',
    'RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Foundation',
    'Heating','GarageType','SaleType','SaleCondition']

for col in frequency_cols:
    freq = data[col].value_counts().to_dict()
    data[col] = data[col].map(freq)

"""# MANUAL ENCODING:"""

manual_cols = {'ExterQual': {'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'ExterCond': {'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'BsmtQual': {'NA':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'BsmtCond': {'NA':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'HeatingQC': {'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'KitchenQual': {'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'FireplaceQu': {'NA':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'GarageQual': {'NA':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'GarageCond': {'NA':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5},
'BsmtExposure': {'NA':0, 'No':1, 'Mn':2, 'Av':3, 'Gd':4},
'BsmtFinType1': {'NA':0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6},
'BsmtFinType2': {'NA':0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6},
'Functional': {'Sal':1,'Sev':2,'Maj2':3,'Maj1':4,'Mod':5,'Min2':6,'Min1':7,'Typ':8},
'GarageFinish': {'NA':0, 'Unf':1, 'RFn':2, 'Fin':3},
'Electrical': {'Mix':1,'FuseP':2,'FuseF':3,'FuseA':4,'SBrkr':5}}

for col, mapping in manual_cols.items():
  data[col] = data[col].map(mapping)



for col in manual_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(x=data[col])
    plt.title(f"{col} After Encoding")
    plt.xlabel("Encoded Values")
    plt.ylabel("Count")
    plt.show()

data.head().T

"""HEAT MAP"""

plt.figure(figsize=(100,100))
sns.heatmap(data.corr(numeric_only=True),annot=True,annot_kws={'size':20})
plt.xticks(fontsize=30,rotation=90)
plt.yticks(fontsize=30,rotation=45)
plt.show()

"""#          REASON
* Very high correlation between GarageCars and GarageArea
* Keeping  GarageCars and droping  GarageArea because:
    * GarageCars directly represents garage capacity.
    * It is easier to interpret.
    * It usually has a slightly stronger relationship with SalePrice.
"""

data.drop('GarageArea', axis=1, inplace=True)

"""SPLITING DATA"""

x=data.drop('SalePrice',axis=1)
y=data['SalePrice']

x

y

"""split data for training and testing:"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

print(x_train.isnull().sum())
print(x_test.isnull().sum())

"""HANDLING MISSING VALUES"""

x=x.fillna(x.mean(numeric_only=True))

"""STANDARD SCALING:"""

x_train_scaled = pd.DataFrame(
    x_train_scaled,
    columns=x_train.columns
)

x_test_scaled = pd.DataFrame(
    x_test_scaled,
    columns=x_test.columns
)

x_train_scaled.head()

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

y_train_scaled=scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled=scaler.transform(y_test.values.reshape(-1, 1))

data.isnull().sum()

"""** MACHINE LEARNING MODEL BUILDING ** :

LINEAR REGRESSION:
"""

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train_scaled,y_train_scaled)

y_pred=model.predict(x_test_scaled)

""" Coefficient of x"""

model.coef_

model.intercept_

"""EVALUATE THE MODEL"""

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
import numpy as np

MSE=mean_squared_error(y_test_scaled,y_pred)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""LASSO (L1 REGULARIZATION)"""

from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.1)

lasso.fit(x_train_scaled,y_train_scaled)

y_pred =lasso.predict(x_test_scaled)

mse=mean_squared_error(y_test_scaled,y_pred)

print(f'mean squared error:{mse}')
print(f'MAE:{ mean_absolute_error(y_test_scaled,y_pred)}')
print(f'RMSE:{np.sqrt(mean_squared_error(y_test_scaled,y_pred))}')
print(f'R-Squared:{r2_score(y_test_scaled,y_pred)}')

print('coefficients:',lasso.coef_)
print('intercept:',lasso.intercept_)

"""RIDGE (L2 REGULARIZATION)"""

from sklearn.linear_model import Ridge
ridge=Ridge(alpha=0.1)
ridge.fit(x_train,y_train)
y_pred=ridge.predict(x_test)

print(f'mean squared error:{mean_squared_error(y_test_scaled,y_pred)}')
print(f'MAE:{ mean_absolute_error(y_test_scaled,y_pred)}')
print(f'RMSE:{np.sqrt(mean_squared_error(y_test_scaled,y_pred))}')
print(f'R-Squared:{r2_score(y_test_scaled,y_pred)}')

print('coefficients:',ridge.coef_)
print('intercept:',ridge.intercept_)

""" Model Fittting:"""

from sklearn.neighbors import KNeighborsRegressor

"""OPTIMAL K    METHOD"""

error_rate=[]
for i in range(2,11):
    kmodel=KNeighborsRegressor(n_neighbors=i)
    kmodel.fit(x_train_scaled,y_train_scaled)
    y_pred1=kmodel.predict(x_test_scaled)
    error_rate.append(np.mean(y_pred1!=y_test_scaled))
plt.plot(range(2,11),error_rate,marker='*')
plt.title('optimal K method')
plt.xlabel('K value')
plt.ylabel('error_rate')
plt.show()

kmodel=KNeighborsRegressor(n_neighbors=4)

kmodel.fit(x_train_scaled,y_train_scaled)

y_pred1=kmodel.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

MSE=mean_squared_error(y_test_scaled,y_pred1)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred1)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred1)

adj_r2=1-(1-0.7930251266127815)*(292-1)/(292-74-1)
adj_r2

"""# support vector regressor model(SVR):"""

from sklearn.svm import SVR
svRegressor =SVR()                                     # as base model with default parameters.
svRegressor.fit(x_train_scaled,y_train_scaled)

y_pred2=svRegressor.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

MSE=mean_squared_error(y_test,y_pred2)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred2)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred2)

adj_r2=1-(1-0.7736408490364224)*(292-1)/(292-74-1)
adj_r2

print(x.isnull().sum())

x.dtypes

"""CROSS VALIDATION SCORE:

"""

from sklearn.model_selection import cross_val_score
scores=cross_val_score(svRegressor,x,y,cv=3,scoring='r2')
print(scores)
print('Cross validation Score:',scores.mean())
print('Std:',scores.std())

"""RANDOM   FOREST  REGRESSOR:"""

from sklearn.ensemble import RandomForestRegressor
Rmodel=RandomForestRegressor()
Rmodel.fit(x_train_scaled,y_train_scaled)

y_pred3=model.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

MSE=mean_squared_error(y_test_scaled,y_pred3)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred3)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred3)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""DECISION TREE REGRESSOR:"""

from sklearn.tree import DecisionTreeRegressor
Dmodel=DecisionTreeRegressor()
Dmodel.fit(x_train_scaled,y_train_scaled)

y_pred4=model.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

MSE=mean_squared_error(y_test_scaled,y_pred4)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred4)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred4)

adj_r2=(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""BAGGING REGRESSOR:"""

from sklearn.ensemble import BaggingRegressor
model_bagg=BaggingRegressor(estimator=svRegressor,n_estimators=50)
model_bagg.fit(x_train_scaled,y_train_scaled)

y_pred5=model_bagg.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

MSE=mean_squared_error(y_test_scaled,y_pred5)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred5)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred5)

adj_r2=1-(1-0.7637855774743969)*(292-1)/(292-74-1)
adj_r2

"""GRADIENT BOOSTING REGRESSOR:"""

from sklearn.ensemble import GradientBoostingRegressor
gb=GradientBoostingRegressor(n_estimators=120)
gb.fit(x_train_scaled,y_train_scaled)

y_pred6=gb.predict(x_test_scaled)

"""EVALUATE THE MODEL"""

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

MSE=mean_squared_error(y_test_scaled,y_pred6)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred6)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred6)

adj_r2=1-(1-0.9018775832566488)*(292-1)/(292-74-1)
adj_r2

!pip install xgboost

"""XGB REGRESSOR:"""

from xgboost import XGBRegressor
Xmodel=XGBRegressor()
Xmodel.fit(x_train_scaled,y_train_scaled)

y_pred7=model.predict(x_test_scaled)

"""EVALUATION THE MODEL"""

MSE=mean_squared_error(y_test_scaled,y_pred7)
MSE

MAE=mean_absolute_error(y_test_scaled,y_pred7)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_pred7)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""BEST MODEL FOR COMPARISON AND TUNING

| Model | R² Score |
|--------|----------|
|Gradient Boosting | 0.90187|
| Random Forest | 0.84151|
| XGBoost| 0.84151 |

Gradient Boosting Regressor:
"""

from sklearn.ensemble import GradientBoostingRegressor
gb1=GradientBoostingRegressor(n_estimators=120)
gb1.fit(x_train_scaled,y_train_scaled)

y_predg=gb.predict(x_test_scaled)

"""EVALUATION"""

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

MSE=mean_squared_error(y_test_scaled,y_predg)
MSE

MAE=mean_absolute_error(y_test_scaled,y_predg)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_predg)

adj_r2=1-(1-0.9018775832566488)*(292-1)/(292-74-1)
adj_r2

"""HYPER PARAMETER TUNING"""

from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[100,500],
            'learning_rate':[0.05,0.1],
            'max_depth':[3,5],
            'min_samples_split':[2,5],
            'subsample':[0.8,1.0]}

grid=GridSearchCV(gb,param_grid,cv=5,scoring='r2')
grid.fit(x_train_scaled,y_train_scaled)

print(grid.best_params_)

model_gb1=GradientBoostingRegressor(n_estimators=500,learning_rate=0.05,max_depth=3,min_samples_split=2,subsample= 0.8)
model_gb1.fit(x_train_scaled,y_train_scaled)

y_predict=model_gb1.predict(x_test_scaled)

"""EVALUATION:"""

MSE=mean_squared_error(y_test_scaled,y_predict)
MSE

MAE=mean_absolute_error(y_test_scaled,y_predict)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_predict)

adj_r2=1-(1-0.9102892485223014)*(292-1)/(292-74-1)
adj_r2

"""RANDOM FOREST REGRESSOR:"""

from sklearn.ensemble import RandomForestRegressor
model1=RandomForestRegressor()
model1.fit(x_train_scaled,y_train_scaled)

Ry_pred=model.predict(x_test_scaled)

"""EVALUATION"""

MSE=mean_squared_error(y_test_scaled,Ry_pred)
MSE

MAE=mean_absolute_error(y_test_scaled,Ry_pred)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,Ry_pred)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""HYPER PARAMETER TUNING:"""

from sklearn.model_selection import RandomizedSearchCV
n_estimators=[int(x) for x in np.linspace(start=200,stop=2000,num=10)]
max_features=['auto','sqrt']
max_depth=[int(x) for x in np.linspace(10,110,num=11)]
max_depth.append(None)
min_samples_split=[2,5,10]
min_samples_leaf=[1,2,4]
bootstrap=[True,False]

random_grid={'n_estimators':n_estimators,'max_features':max_features,'max_depth':max_depth,
             'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,
             'bootstrap':bootstrap}

rf_clf1=RandomForestRegressor()  # model

rf_cv=RandomizedSearchCV(estimator=rf_clf1,scoring='r2',param_distributions=random_grid,
                         n_iter=100,cv=3,verbose=2,n_jobs=1)

rf_cv.fit(x_train,y_train)
rf_best_params=rf_cv.best_params_
print(f'best parameters:{rf_best_params})')

print(f'best parameters:{rf_best_params})')

rf_clf2=RandomForestRegressor(n_estimators=1800, min_samples_split= 2, min_samples_leaf=1,
                               max_features= 'sqrt', max_depth= 70, bootstrap= False)

rf_clf2.fit(x_train_scaled,y_train_scaled)

y_predict1=rf_clf2.predict(x_test_scaled)

"""EVALUATION"""

MSE=mean_squared_error(y_test_scaled,y_predict1)
MSE

MAE=mean_absolute_error(y_test_scaled,y_predict1)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,y_predict1)

adj_r2=1-(1-0.8953152138050879)*(292-1)/(292-74-1)
adj_r2

"""XGB REGRESSOR(XGBoost)"""

from xgboost import XGBRegressor
modelX=XGBRegressor()
modelX.fit(x_train_scaled,y_train_scaled)

Xy_pred=model.predict(x_test_scaled)

"""EVALUATION"""

MSE=mean_squared_error(y_test_scaled,Xy_pred)
MSE

MAE=mean_absolute_error(y_test_scaled,Xy_pred)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,Xy_pred)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""HYPER PARAMETER TUNING"""

from sklearn.model_selection import RandomizedSearchCV

param_dist={'gamma':[0,0.1,0.2,0.4,0.8,1.6,3.2,6.4,12.8,25.6,51.2,102.4,200],
            'learning_rate':[0.01,0.03,0.06,0.1,0.15,0.2,0.25,0.300000012,0.4,0.5,0.6,0.7],
            'max_depth':[5,6,7,8,9,10,11,12,13,14],
            'n_estimators':[50,65,80,100,115,130,150],
            'reg_alpha':[0,0.1,0.2,0.4,0.8,1.6,3.2,6.4,12.8,25.6,51.2,102.4,200],
            'reg_lambda':[0,0.1,0.2,0.4,0.8,1.6,3.2,6.4,12.8,25.6,51.2,102.4,200]}

XGB=XGBRegressor()
rcv=RandomizedSearchCV(estimator=XGB,scoring='r2',param_distributions=param_dist,n_iter=100,cv=3,verbose=2,random_state=42)
rcv.fit(x_train_scaled,y_train_scaled)

print(rcv.best_params_)

print(rcv.best_params_)

Xmodel=XGBRegressor(reg_lambda=0.2,reg_alpha=0.8,n_estimators=50,max_depth=5,learning_rate=0.15,gamma=0.4)
Xmodel.fit(x_train_scaled,y_train_scaled)

Xy_pred=model.predict(x_test_scaled)

"""EVALUATION"""

MSE=mean_squared_error(y_test_scaled,Xy_pred)
MSE

MAE=mean_absolute_error(y_test_scaled,Xy_pred)
MAE

rmse=np.sqrt(MSE)
rmse

r2_score(y_test_scaled,Xy_pred)

adj_r2=1-(1-0.8415177450777361)*(292-1)/(292-74-1)
adj_r2

"""| Model                      | R² Score |
|----------------------------|----------|
|Gradient Boosting Regressor | 0.91028|
| Random Forest Regressor    | 0.89531|
| XGBoost Regressor          | 0.84151 |

Best Model

Model  : Gradient Boosting Regressor

R² Score  : 0.91028

NOTE :
    
    After hyperparameter tuning, the Gradient Boosting Regressor
    achieved the highest R² score of 0.91028.
    Outperforming XGBoost Regressor (0.84151) and Random Forest Regressor (0.89531).
    Therefore, Gradient Boosting Regressor was selected as the final model for house price prediction.

## R2 scores of models before hyperparameter tuning :

| Model             | R² Score |
| ----------------- | -------: |
| Linear Regression |   0.84151|
| KNN Regressor     |   0.79302|
| Support Vector Regressor(SVR)               |   0.77364|
| Random Forest     |   0.84151|
|Decision Tree Regressor |0.84151
Bagging Regressor	|0.76378
| XGBoost           |   0.84151 |
| Gradient Boosting |   0.90187|

## R2 scores after hyperparameter tuning

| Model                       | Tuned R² Score |
| --------------------------- | -------------: |
|Gradient Boosting Regressor |        0.91028|
| Random Forest Regressor     |        0.89531|
| XGBoost Regressor           |        0.84151|

## Best Model

### Gradient Boosting Regressor

* R² Score: 0.91028
* Explains approximately 91.10% of the variation in house prices.
* Achieved the highest prediction accuracy among all evaluated models.

### b)   
### Relationship Between Features and House Price

Positive Impact on Price:

* Higher Overall Quality
* Larger Living Area
* More Garage Capacity
* Larger Basement Area
* More Bathrooms
* Newer Construction Year

Negative Impact on Price:

* Older houses
* Poor quality ratings
* Smaller living area
* Less desirable locations

Therefore, house prices increase significantly with improvements in quality, size, amenities, and neighborhood desirability.

# Task 3: Customer Recommendations

## Recommendations Based on Area

### Budget-Friendly Buyers

* Consider houses with moderate living area.
* Look for properties in developing neighborhoods.
* Older houses with renovation potential provide better affordability.

### Mid-Range Buyers

* Focus on neighborhoods with good schools and infrastructure.
* Choose houses with average to above-average quality ratings.
* Consider properties with garage and basement facilities.

### Premium Buyers

* Prefer houses with high Overall Quality ratings.
* Select properties with larger living area and garage capacity.
* Consider newer constructions located in premium neighborhoods.

## Recommendations Based on Price

Low Price Range:

* Smaller houses
* Older construction
* Limited amenities

Medium Price Range:

* Moderate area
* Good neighborhood
* Standard facilities

High Price Range:

* Large living area
* Excellent construction quality
* Multiple bathrooms and garages
* Premium neighborhood location

## Final Recommendation

Customers should prioritize:

1. Neighborhood quality
2. Overall house quality
3. Living area
4. Garage capacity
5. Basement size

The developed Gradient Boosting Regressor model can be used to estimate house prices accurately and assist customers in making informed purchasing decisions.

# Challenges Faced and Solutions Implemented

## 1. Missing Values

### Challenge

Several features contained missing values, including:

* LotFrontage
* Alley
* PoolQC
* Fence
* MiscFeature
* Garage-related features
* Basement-related features

### Solution

* Numerical columns were imputed using median values.
* Categorical columns were imputed using mode values.
* Columns with extremely high missing percentages were removed.

### Reasoning

Median imputation is robust against outliers, while mode imputation preserves the most common category. Removing highly incomplete columns reduces noise and improves model quality.



## 2. Categorical Features

### Challenge

Many variables were stored as text and could not be used directly by machine learning algorithms.

### Solution

Categorical variables were converted into numerical format using encoding techniques.

### Reasoning

Machine learning algorithms require numerical inputs for model training.


## 3. Outliers

### Challenge

Some features contained extreme values that could affect model performance.

### Solution

Outliers were identified using boxplots and distribution analysis.

### Reasoning

Outlier detection helps improve model stability and reduces the impact of unusual observations.


## 4. Multicollinearity

### Challenge

Several numerical variables showed strong correlations with each other.

### Solution

Correlation analysis and heatmaps were used to understand feature relationships.

### Reasoning

Understanding feature dependency helps interpret model behavior and avoid redundant information.



## 5. Model Selection

### Challenge

Different machine learning algorithms produced different prediction accuracies.

### Solution

Multiple regression models were trained and compared using the R² metric.

### Reasoning

Model comparison helps identify the algorithm that best captures relationships within the housing dataset.



## 6. Hyperparameter Optimization

### Challenge

Default model parameters did not always provide optimal performance.

### Solution

Hyperparameter tuning was performed for:

* Random Forest Regressor
* XGBoost Regressor
* Gradient Boosting Regressor

### Reasoning

Tuning improves predictive performance by identifying the most suitable parameter combinations.



## 7. Feature Importance Interpretation

### Challenge

Determining which features most influenced house prices.

### Solution

Correlation analysis and feature importance evaluation were performed.

### Key Influential Features

* OverallQual
* GrLivArea
* GarageCars
* GarageArea
* TotalBsmtSF
* YearBuilt

### Reasoning

Understanding feature importance enables better business recommendations and customer decision-making.

## Final Conclusion

Despite challenges related to missing values, categorical variables, and model selection, effective preprocessing and hyperparameter tuning resulted in a highly accurate house price prediction model. The final Gradient Boosting Regressor achieved an R² score of 0.91028 and was selected for production deployment.
"""

